name: pgdev
channels:
  - conda-forge
  - defaults
  - gimli
dependencies:
  - pgcore >= 1.2.4
  - matplotlib
  - jupyter
  - sphinx >= 1.8.5
  - pytest
  - numpy
  - scipy
  - pytest-cov
  - pytest-html
  - sphinx-gallery
  - sphinxcontrib-bibtex
  - sphinxcontrib-programoutput
  - sphinxcontrib-spelling
  - sphinxcontrib-doxylink
  - scipy
  - bibtexparser
  - pyvista=0.33
  - meshio
  - tetgen
  - panel
